/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'OA10249' at '3/22/16 3:05 PM' with Gradle 2.11
 *
 * @author OA10249, @date 3/22/16 3:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
